enable-module-update = true # set this to false if you do not want to receive updates for the module
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

[YouTube-Morphe]
enabled = true
app-name = "YouTube"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-desktop"
rv-brand = "Morphe"
build-mode = "both" # Options 'apk', 'module', or 'both'
arch = "arm64-v8a" # Options 'arm64-v8a', 'armeabi-v7a', 'x86', 'x86_64', or 'universal'
# Stable Support #
# version = "auto" # "21.04.223"
# Experimental Support #
# version = "21.28.207" # Version Supporting Miniplayer Type
# version = "21.32.6"
# version = "21.33.325"
version = "21.34.243-SECONDARY"
excluded-patches = """\
    'Custom branding name for YouTube' \
    'Custom branding icon for YouTube' \
    'Custom branding' \
    """
# included-patches = ""
patches-version = "dev" # Options 'latest', 'dev', or A specific version tag
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
github-dlurl = "https://github.com/dj-tanjid/AppRepo/releases/tag/com.google.android.youtube"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[YT-Music-Morphe]
enabled = true
app-name = "YT Music"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-desktop"
rv-brand = "Morphe"
build-mode = "both" # Options 'apk', 'module', or 'both'
arch = "arm64-v8a" # Options 'arm64-v8a', 'armeabi-v7a', 'x86', 'x86_64', or 'universal'
# Stable Support #
# version = "auto" # "9.15.51"
# Experimental Support #
# version = "9.32.51"
version = "9.33.52"
excluded-patches = """\
    'Custom branding name for YouTube Music' \
    'Custom branding icon for YouTube Music' \
    'Custom branding' \
    """
# included-patches = ""
patches-version = "dev" # Options 'latest', 'dev', or A specific version tag
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"

[Reddit-Morphe]
enabled = true
app-name = "Reddit"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-desktop"
rv-brand = "Morphe"
build-mode = "both" # Options 'apk', 'module', or 'both'
# Stable Support #
# version = "auto" # "2026.14.0"
# Experimental Support #
# version = "2026.31.1"
# version = "2026.32.0"
version = "2026.34.0"
dpi = "120-640dpi" # Options '120-640dpi', or 'nodpi'
excluded-patches = """\
    'Custom branding name for Reddit' \
    'Custom branding icon for Reddit' \
    'Custom branding' \
    """
# included-patches = ""
patches-version = "dev" # Options 'latest', 'dev', or A specific version tag
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.reddit.frontpage"

[Google-Photos-De-Vanced]
enabled = false
app-name = "Google Photos"
patches-source = "RookieEnough/De-Vanced"
cli-source = "MorpheApp/morphe-desktop"
rv-brand = "De-Vanced"
arch = "arm64-v8a" # Options 'arm64-v8a', 'armeabi-v7a', 'x86', 'x86_64', or 'universal'
# version = "auto"
# version = "7.88.0.966185373"
version = "7.89.0.968035987"
build-mode = "both" # Options 'apk', 'module', or 'both'
# patches-version = "dev" # Options 'latest', 'dev', or A specific version tag
included-patches = """\
    'Enable DCIM folders backup control' \
    'Fix DCIM folder classification' \
    'Remove screenshot restriction' \
    'Remove screen capture restriction' \
    'Spoof features' \
    """
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.photos"

[Facebook-De-Vanced]
enabled = false
app-name = "Facebook"
pkg-name = "com.facebook.katana"
patches-source = "RookieEnough/De-Vanced"
cli-source = "MorpheApp/morphe-desktop"
rv-brand = "De-Vanced"
arch = "arm64-v8a"
# version = "latest"
version = "490.0.0.63.82"
build-mode = "apk"
github-dlurl = "https://github.com/dj-tanjid/AppRepo/releases/tag/com.facebook.katana"
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-technologies-llc/facebook"
uptodown-dlurl = "https://facebook.en.uptodown.com/android"

[Facebook-Messenger-De-Vanced]
enabled = false
app-name = "Facebook Messenger"
pkg-name = "com.facebook.orca"
patches-source = "RookieEnough/De-Vanced"
cli-source = "MorpheApp/morphe-desktop"
rv-brand = "De-Vanced"
arch = "arm64-v8a"
version = "latest"
build-mode = "apk"
github-dlurl = "https://github.com/dj-tanjid/AppRepo/releases/tag/com.facebook.orca"
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-technologies-llc/messenger"
uptodown-dlurl = "https://facebook-messenger.en.uptodown.com/android"

[Threads-De-Vanced]
enabled = false
app-name = "Threads"
pkg-name = "com.instagram.barcelona"
patches-source = "RookieEnough/De-Vanced"
cli-source = "MorpheApp/morphe-desktop"
rv-brand = "De-Vanced"
arch = "arm64-v8a"
version = "latest"
build-mode = "apk"
github-dlurl = "https://github.com/dj-tanjid/AppRepo/releases/tag/com.instagram.barcelona"
apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/threads-an-instagram-app"
uptodown-dlurl = "https://threads.en.uptodown.com/android"

[Twitter-Piko]
enabled = true
app-name = "Twitter"
patches-source = "crimera/piko"
cli-source = "MorpheApp/morphe-desktop"
rv-brand = "Piko"
build-mode = "apk" # Options 'apk', 'module', or 'both'
version = "latest"
# version = "12.15.2-release.0"
include-stock = "split" # Options 'split', 'merged', or 'disable'
patches-version = "dev" # Options 'latest', 'dev', or A specific version tag
included-patches = """\
    'Bring back twitter' \
    'Browse tweet object' \
    'Dynamic color' \
    """
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter"
uptodown-dlurl = "https://twitter.en.uptodown.com/android"
github-dlurl = "https://github.com/dj-tanjid/AppRepo/releases/tag/com.twitter.android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.twitter.android"

[X-Piko]
enabled = true
app-name = "X"
patches-source = "crimera/piko"
cli-source = "MorpheApp/morphe-desktop"
rv-brand = "Piko"
build-mode = "apk" # Options 'apk', 'module', or 'both'
version = "latest"
# version = "12.15.2-release.0"
include-stock = "split" # Options 'split', 'merged', or 'disable'
patches-version = "dev" # Options 'latest', 'dev', or A specific version tag
included-patches = """\
    'Dynamic color' \
    'Browse tweet object' \
    """
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter"
uptodown-dlurl = "https://twitter.en.uptodown.com/android"
github-dlurl = "https://github.com/dj-tanjid/AppRepo/releases/tag/com.twitter.android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.twitter.android"

[Instagram-Piko]
enabled = true
app-name = "Instagram"
patches-source = "crimera/piko"
cli-source = "MorpheApp/morphe-desktop"
rv-brand = "Piko"
build-mode = "apk" # Options 'apk', 'module', or 'both'
version = "latest"
# version = "12.15.2-release.0"
patches-version = "dev" # Options 'latest', 'dev', or A specific version tag
included-patches = """\
    'Theme' \
    """
excluded-patches = """\
    'Unlock Plus benefits' \
    """
apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/instagram-instagram"
uptodown-dlurl = "https://instagram.en.uptodown.com/android"
# github-dlurl = "https://github.com/krvstek/uni-storage/releases/tag/instagram"
github-dlurl = "https://github.com/dj-tanjid/AppRepo/releases/tag/com.instagram.android"
