enable-module-update = true # set this to false if you do not want to receive updates for the module
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

[YouTube-Morphe]
enabled = true
app-name = "YouTube"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-desktop"
rv-brand = "Morphe"
build-mode = "both" # Options 'apk', 'module', or 'both'
arch = "arm64-v8a" # Options 'arm64-v8a', 'armeabi-v7a', 'x86', 'x86_64', or 'universal'
# Stable Support #
# version = "auto" # "21.04.223"
# Experimental Support #
# version = "21.28.207" # Version Supporting Miniplayer Type
# version = "21.31.525"
version = "21.32.3"
excluded-patches = """\
    'Custom branding name for YouTube' \
    'Custom branding icon for YouTube' \
    'Custom branding' \
    """
# included-patches = ""
patches-version = "dev" # Options 'latest', 'dev', or A specific version tag
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[YT-Music-Morphe]
enabled = true
app-name = "YT Music"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-desktop"
rv-brand = "Morphe"
build-mode = "both" # Options 'apk', 'module', or 'both'
arch = "arm64-v8a" # Options 'arm64-v8a', 'armeabi-v7a', 'x86', 'x86_64', or 'universal'
# Stable Support #
# version = "auto" # "9.15.51"
# Experimental Support #
# version = "9.29.54"
# version = "9.30.52"
version = "9.31.54"
excluded-patches = """\
    'Custom branding name for YouTube Music' \
    'Custom branding icon for YouTube Music' \
    'Custom branding' \
    """
# included-patches = ""
patches-version = "dev" # Options 'latest', 'dev', or A specific version tag
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"

[YouTube-Anddea]
enabled = false
app-name = "YouTube"
patches-source = "anddea/revanced-patches"
# patches-source = "inotia00/revanced-patches"
cli-source = "MorpheApp/morphe-cli"
# cli-source = "inotia00/revanced-cli"
rv-brand = "Anddea Extended"
version = "20.21.37"
patches-version = "dev"
build-mode = "both" # Options 'apk', 'module', or 'both'
excluded-patches = " 'Enable debug logging' "
# included-patches = ""
# include-stock = true
# exclusive-patches = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[YT-Music-Anddea]
enabled = false
app-name = "YT Music"
patches-source = "anddea/revanced-patches"
# patches-source = "inotia00/revanced-patches"
cli-source = "MorpheApp/morphe-cli"
# cli-source = "inotia00/revanced-cli"
rv-brand = "Anddea Extended"
version = "auto"
arch = "arm64-v8a" # Options 'arm64-v8a', 'armeabi-v7a', 'x86', 'x86_64', or 'universal'
patches-version = "dev" # Options 'latest', 'dev', or A specific version tag
build-mode = "both" # Options 'apk', 'module', or 'both'
excluded-patches = " 'Enable debug logging' "
included-patches = " 'Hide player overlay filter' 'Hide overlay filter' 'Disable music video in album' "
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"

[Reddit-Morphe]
enabled = true
app-name = "Reddit"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-desktop"
rv-brand = "Morphe"
build-mode = "both" # Options 'apk', 'module', or 'both'
# Stable Support #
# version = "auto" # "2026.14.0"
# Experimental Support #
# version = "2026.30.0"
version = "2026.31.1"
# version = "2026.32.0"
dpi = "120-640dpi" # Options '120-640dpi', or 'nodpi'
excluded-patches = """\
    'Custom branding name for Reddit' \
    'Custom branding icon for Reddit' \
    'Custom branding' \
    """
# included-patches = ""
patches-version = "dev" # Options 'latest', 'dev', or A specific version tag
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.reddit.frontpage"

[Google-Photos-De-Vanced]
enabled = false
app-name = "Google Photos"
patches-source = "RookieEnough/De-Vanced"
cli-source = "MorpheApp/morphe-desktop"
rv-brand = "De-Vanced"
arch = "arm64-v8a" # Options 'arm64-v8a', 'armeabi-v7a', 'x86', 'x86_64', or 'universal'
# version = "auto"
# version = "7.86.0.956040398"
version = "7.87.0.957333026"
build-mode = "both" # Options 'apk', 'module', or 'both'
# patches-version = "dev" # Options 'latest', 'dev', or A specific version tag
included-patches = """\
    'Enable DCIM folders backup control' \
    'Fix DCIM folder classification' \
    'Remove screenshot restriction' \
    'Remove screen capture restriction' \
    'Spoof features' \
    """
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.photos"

[Facebook-De-Vanced]
enabled = false
app-name = "Facebook"
patches-source = "RookieEnough/De-Vanced"
cli-source = "MorpheApp/morphe-desktop"
rv-brand = "De-Vanced"
arch = "arm64-v8a" # Options 'arm64-v8a', 'armeabi-v7a', 'x86', 'x86_64', or 'universal'
version = "latest"
# version = "573.0.0.37.74"
build-mode = "apk" # Options 'apk', 'module', or 'both'
# patches-version = "dev" # Options 'latest', 'dev', or A specific version tag
# included-patches = ""
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-technologies-llc/facebook"
uptodown-dlurl = "https://facebook.en.uptodown.com/android"

[Facebook-Messenger-De-Vanced]
enabled = false
app-name = "Facebook Messenger"
patches-source = "RookieEnough/De-Vanced"
cli-source = "MorpheApp/morphe-desktop"
rv-brand = "De-Vanced"
arch = "arm64-v8a" # Options 'arm64-v8a', 'armeabi-v7a', 'x86', 'x86_64', or 'universal'
version = "latest"
# version = "573.0.0.44.88"
build-mode = "apk" # Options 'apk', 'module', or 'both'
# patches-version = "dev" # Options 'latest', 'dev', or A specific version tag
# included-patches = ""
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-technologies-llc/messenger"
uptodown-dlurl = "https://facebook-messenger.en.uptodown.com/android"

[Threads-De-Vanced]
enabled = false
app-name = "Threads"
patches-source = "RookieEnough/De-Vanced"
cli-source = "MorpheApp/morphe-desktop"
rv-brand = "De-Vanced"
arch = "arm64-v8a" # Options 'arm64-v8a', 'armeabi-v7a', 'x86', 'x86_64', or 'universal'
version = "latest"
# version = "441.0.0.44.81"
build-mode = "apk" # Options 'apk', 'module', or 'both'
# patches-version = "dev" # Options 'latest', 'dev', or A specific version tag
# included-patches = ""
apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/threads-an-instagram-app"
uptodown-dlurl = "https://threads.en.uptodown.com/android"

[Twitter-Piko]
enabled = false
app-name = "Twitter"
patches-source = "crimera/piko"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Piko"
build-mode = "apk" # Options 'apk', 'module', or 'both'
# version = "auto"
version = "11.81.0-release.0" # PairIP Free
include-stock = "split" # Options 'split', 'merged', or 'disable'
patches-version = "dev" # Options 'latest', 'dev', or A specific version tag
included-patches = """\
    'Bring back twitter' \
    'Dynamic color' \
    """
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter"
uptodown-dlurl = "https://twitter.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.twitter.android"

[X-Piko]
enabled = false
app-name = "X"
patches-source = "crimera/piko"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Piko"
build-mode = "apk" # Options 'apk', 'module', or 'both'
version = "auto"
# version = "11.81.0-release.0" # PairIP Free
include-stock = "split" # Options 'split', 'merged', or 'disable'
patches-version = "dev" # Options 'latest', 'dev', or A specific version tag
included-patches = """\
    'Dynamic color' \
    """
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter"
uptodown-dlurl = "https://twitter.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.twitter.android"

